# Generated by Django 4.2.6 on 2024-01-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session',
            field=models.BooleanField(default=False),
        ),
    ]
