# Generated by Django 4.2.6 on 2024-01-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_table_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.table')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.table')),
            ],
        ),
    ]
