# Generated by Django 4.2.6 on 2024-01-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_table_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
    ]
