# Generated by Django 4.2.6 on 2024-01-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table_number',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='table_number',
            new_name='table',
        ),
    ]
